#!/usr/local/bin/python

import sys
import json
from tahoma.protocol import Protocol
from tahoma.action import Action

# open the credentials file. This works from within the container only...
creds = open('/config/.tahoma.credentials').read()
creds = json.loads(creds)

def execTahomaCommand(devname, cmd):
    tahoma = Protocol(creds['USERNAME'], creds['PASSWORD'], '.tahoma.cookie')
    tahoma.getSetup()
    devs = tahoma.getDevices()
    for d in devs.keys():
        if devs[d].label == devname:
            #print('Execute on device %s, label %s' % (d, devs[d].label))
            a = Action(d)
            a.addCommand(cmd)
            tahoma.applyActions('hass', [a])
            return 0
    return -1

if len(sys.argv) != 3:
    print('Usage: pytahoma device_label command')
    sys.exit(-1)

devname = sys.argv[1]
cmd = sys.argv[2]
if execTahomaCommand(devname, cmd):
    print('Device %s not found' % devname)
    sys.exit(-2)
